1.2.1 Пример
Задача:
Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.
Решение:

In [1]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


1.2.2 Пример 
Задача: 
Пример. Выполнить следующее: 
1.Создать вектор (одномерный массив) размера 10, заполненный нулями. 
2.Создать вектор размера 10, заполненный единицами. 
3.Создать вектор размера 10, заполненный заданным числом. 
4.Создать вектор со значениями от 10 до 19. 
Решение:

In [10]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


1.2.3 Пример 
Задача: 
Создать массив 10x10 со случайными значениями, найти минимум, максимум и среднее значение.
Решение:

In [9]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.0310722067609448 0.979082546632387 0.5122743161164022


1.2.4 Пример 
Задача: 
Задать матрицу размерности 5 на 5 и п оменять 2 строки в матрице местами.
Решение:

In [8]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


1.2.5 Пример 
Задача: 
Выяснить результат следующих выражений : 
0 * np.nan 
np.nan == np.nan 
np.inf > np.nan 
np.nan - np.nan 
0.3 == 3 * 0.1 
Решение:

In [6]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3*0.1)

nan
False
False
nan
False


1.2.6 Пример 
Задача: 
Отсортировать массив. 
Решение: 

In [7]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


1.3.1 Задание 
Задача: 
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 
Решение: 

In [51]:
A = np.arange(64).reshape(8, 8)
for i in range(8):
    for j in range(8):
        A[i, j] = np.ones(1)
        if (i%2==0 and j%2==0) or (i%2==1 and j%2==1):
            A[i, j] = np.zeros(1)
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


1.3.2 Задание 
Задача: 
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.

In [50]:
a = np.zeros(25).reshape(5, 5)
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


1.3.3 Задание 
Задача: 
Создать массив 3x3x3 со случайными значениями. 
Решение: 

In [73]:
a = np.random.random((3, 3, 3))
print(a)

[[[0.90688414 0.81216631 0.20598987]
  [0.57426751 0.56616739 0.53864504]
  [0.08292399 0.08130899 0.36744678]]

 [[0.89766127 0.59856054 0.58072269]
  [0.15748825 0.18369276 0.10619226]
  [0.51660862 0.95723385 0.8929108 ]]

 [[0.03678905 0.84635079 0.10249631]
  [0.99191422 0.09398875 0.49727706]
  [0.47513393 0.15942859 0.40380962]]]


1.3.4 Задание 
Задача: 
Создать матрицу с 0 внутри, и 1 на границах 

In [68]:
a = np.zeros((5, 5))
for i in range(5):
    for j in range(5):
        if (i==0 and 0<=j<=4) or (j==4 and 0<=i<=4) or (j==0 and 0<=i<=4) or (i==4 and 0<=j<=4):
            a[i, j] = np.ones(1)
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


1.3.5 Задание 
Задача: 
Создайте массив и отсортируйте его по убыванию. 
Решение: 

In [69]:
a = np.array([3, 1, 9, 10, 67, 4, 8])
print(-np.sort(-a))

[67 10  9  8  4  3  1]


1.3.6 Задание 
Задача: 
Создайте матрицу, выведите ее форму, размер и размерность. 

In [72]:
a = np.arange(16).reshape(4, 4)
print(a)
print(np.shape(a))
print(np.size(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(4, 4)
16


2.2.1 Пример 
Задача: 
Создать Series из списка Python, словаря Python, и массива Numpy (установить буквенные метки для последнего).  
Решение: 

In [16]:
import pandas as pd
import numpy as np
lst = [1, 2, 3, 4, 5]
d = {'a': 1, 'b': 2, 'c': 3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)
               

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


2.2.2 Пример 
Задача: 
Дано два Series. Напечатать их первые элементы и все элементы после третьего (во втором фрейме).  
Решение: 

In [5]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


2.2.3 Пример 
Задача: 
Создайте новый фрейм данных. 
Решение:

In [22]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

2.2.4 Пример 
Задача: 
Загрузите фрейм данных по ссылке: 
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv
Решение:

In [4]:
import pandas as pd
import pyodide_http
pyodide_http.patch_all()
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

In [ ]:
2.2.5 Пример 
Задача: 
Пронализировать характеристики фрейма данных. 

In [6]:
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

2.2.6 Пример 
Задача: 
Выберите индивидуальные данные или срезы фрейма данных. 
Решение: 

In [7]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

2.2.7 Пример 
Задача: 
Требуется отобрать строки фрейма данных на основе некоторого условия. Необходимо сформировать новый фрейм данных из пассажиров первого класса. 
Решение: 

In [8]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

2.3.1 Задание 
Задача: 
Найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу. 
Решение:

In [12]:
import numpy as np
a = pd.Series([2, 4, 6, 8])
b = pd.Series([1, 3, 5, 7])
sum((a - b)**2)**.5
np.linalg.norm(a-b)

2.0

2.3.2 Задание
Задача:
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [36]:
import pandas as pd
import pyodide_http
pyodide_http.patch_all()
url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'
dataframe = pd.read_csv(url)
dataframe.head(10)

age         workclass  education_num         marital_status  \
0   39         State-gov             13          Never-married   
1   50  Self-emp-not-inc             13     Married-civ-spouse   
2   38           Private              9               Divorced   
3   53           Private              7     Married-civ-spouse   
4   28           Private             13     Married-civ-spouse   
5   37           Private             14     Married-civ-spouse   
6   49           Private              5  Married-spouse-absent   
7   52  Self-emp-not-inc              9     Married-civ-spouse   
8   31           Private             14          Never-married   
9   42           Private             13     Married-civ-spouse   

          occupation   relationship   race  gender  hours_per_week  \
0       Adm-clerical  Not-in-family  White    Male              40   
1    Exec-managerial        Husband  White    Male              13   
2  Handlers-cleaners  Not-in-family  White    Male              40   
3  Handlers-cleaners        Husband  Other    Male              40   
4     Prof-specialty           Wife  Other  Female              40   
5    Exec-managerial           Wife  White  Female              40   
6      Other-service  Not-in-family  Other  Female              16   
7    Exec-managerial        Husband  White    Male              45   
8     Prof-specialty  Not-in-family  White  Female              50   
9    Exec-managerial        Husband  White    Male              40   

  native_country  capital income_status  
0  United-States     2174         <=50K  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K  
4          Other        0         <=50K  
5  United-States        0         <=50K  
6          Other        0         <=50K  
7  United-States        0          >50K  
8  United-States    14084          >50K  
9  United-States     5178          >50K

2.3.3 Задание 
Задача: 
Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7. 
Решение: 

In [37]:
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

age  education_num  hours_per_week       capital
count  45222.000000   45222.000000    45222.000000  45222.000000
mean      38.547941      10.118460       40.938017   1012.834925
std       13.217870       2.552881       12.007508   7530.315380
min       17.000000       1.000000        1.000000  -4356.000000
25%       28.000000       9.000000       40.000000      0.000000
50%       37.000000      10.000000       40.000000      0.000000
75%       47.000000      13.000000       45.000000      0.000000
max       90.000000      16.000000       99.000000  99999.000000

In [38]:
dataframe.iloc[1:4]

age         workclass  education_num      marital_status  \
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   

          occupation   relationship   race gender  hours_per_week  \
1    Exec-managerial        Husband  White   Male              13   
2  Handlers-cleaners  Not-in-family  White   Male              40   
3  Handlers-cleaners        Husband  Other   Male              40   

  native_country  capital income_status  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K

In [39]:
dataframe[dataframe['gender'] == 'Female'].head(5)

age workclass  education_num         marital_status       occupation  \
4    28   Private             13     Married-civ-spouse   Prof-specialty   
5    37   Private             14     Married-civ-spouse  Exec-managerial   
6    49   Private              5  Married-spouse-absent    Other-service   
8    31   Private             14          Never-married   Prof-specialty   
12   23   Private             13          Never-married     Adm-clerical   

     relationship   race  gender  hours_per_week native_country  capital  \
4            Wife  Other  Female              40          Other        0   
5            Wife  White  Female              40  United-States        0   
6   Not-in-family  Other  Female              16          Other        0   
8   Not-in-family  White  Female              50  United-States    14084   
12      Own-child  White  Female              30  United-States        0   

   income_status  
4          <=50K  
5          <=50K  
6          <=50K  
8           >50K  
12         <=50K

3.2.1. Пример 
Задача: 
Прошкалируйте числовой признак в диапазон между двумя значениями. 
Решение:

In [23]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0,1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

3.2.2. Пример 
Задача: 
Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное отклонение 1. 
Решение: 

In [25]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
print("Среднее:", round(standardized.mean()))
print("Стандартно отклонение:", standardized.std())
standardized

Среднее: 0
Стандартно отклонение: 1.0


array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

3.2.3. Пример 
Задача: 
Дан фрейм данных  
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21], 
                           'B'[103.02,107.26,110.35,114.23,114.68], 
                           'C'['big','small','big','small','small']}) 
Необходимо масштабировать его числовые столбцы. 
Решение: 

In [28]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00, 90.20, 90.95, 96.27, 91.21],
                      'B':[103.02, 107.26, 110.35, 114.23, 114.68],
                      'C':['big', 'small', 'big', 'small', 'small']})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

3.3.2 Задание 
Задача: 
Загрузить фрейм данных по ссылке : 
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. 
Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования. 

In [35]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
import pyodide_http
pyodide_http.patch_all()
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
# нормализация первого числового признака (sepal_length_cm) с использованием минимаксного преобразования
scaler1 = MinMaxScaler()
dataframe[['sepal_length_cm']] = scaler1.fit_transform(dataframe[['sepal_length_cm']])
# нормализация второго числового признака (sepal_width_cm) с задействованием z-масштабирования
scaler2 = StandardScaler()
dataframe[['sepal_width_cm']] = scaler2.fit_transform(dataframe[['sepal_width_cm']])

dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]